// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountGroupsColumns holds the columns for the "account_groups" table.
	AccountGroupsColumns = []*schema.Column{
		{Name: "oid", Type: field.TypeUUID},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "external_id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccountGroupsTable holds the schema information for the "account_groups" table.
	AccountGroupsTable = &schema.Table{
		Name:       "account_groups",
		Columns:    AccountGroupsColumns,
		PrimaryKey: []*schema.Column{AccountGroupsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountGroupsTable,
	}
)

func init() {
}
