// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-consumer/ent/accountgroup"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AccountGroup is the model entity for the AccountGroup schema.
type AccountGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID   string `json:"external_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountgroup.FieldDisplayName, accountgroup.FieldExternalID:
			values[i] = new(sql.NullString)
		case accountgroup.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountGroup fields.
func (ag *AccountGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountgroup.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ag.ID = *value
			}
		case accountgroup.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				ag.DisplayName = value.String
			}
		case accountgroup.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				ag.ExternalID = value.String
			}
		default:
			ag.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountGroup.
// This includes values selected through modifiers, order, etc.
func (ag *AccountGroup) Value(name string) (ent.Value, error) {
	return ag.selectValues.Get(name)
}

// Update returns a builder for updating this AccountGroup.
// Note that you need to call AccountGroup.Unwrap() before calling this method if this AccountGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (ag *AccountGroup) Update() *AccountGroupUpdateOne {
	return NewAccountGroupClient(ag.config).UpdateOne(ag)
}

// Unwrap unwraps the AccountGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ag *AccountGroup) Unwrap() *AccountGroup {
	_tx, ok := ag.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountGroup is not a transactional entity")
	}
	ag.config.driver = _tx.drv
	return ag
}

// String implements the fmt.Stringer.
func (ag *AccountGroup) String() string {
	var builder strings.Builder
	builder.WriteString("AccountGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ag.ID))
	builder.WriteString("display_name=")
	builder.WriteString(ag.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(ag.ExternalID)
	builder.WriteByte(')')
	return builder.String()
}

// AccountGroups is a parsable slice of AccountGroup.
type AccountGroups []*AccountGroup
