// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-consumer/ent/accountgroup"
	"go-consumer/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AccountGroupQuery is the builder for querying AccountGroup entities.
type AccountGroupQuery struct {
	config
	ctx        *QueryContext
	order      []accountgroup.OrderOption
	inters     []Interceptor
	predicates []predicate.AccountGroup
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccountGroupQuery builder.
func (agq *AccountGroupQuery) Where(ps ...predicate.AccountGroup) *AccountGroupQuery {
	agq.predicates = append(agq.predicates, ps...)
	return agq
}

// Limit the number of records to be returned by this query.
func (agq *AccountGroupQuery) Limit(limit int) *AccountGroupQuery {
	agq.ctx.Limit = &limit
	return agq
}

// Offset to start from.
func (agq *AccountGroupQuery) Offset(offset int) *AccountGroupQuery {
	agq.ctx.Offset = &offset
	return agq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (agq *AccountGroupQuery) Unique(unique bool) *AccountGroupQuery {
	agq.ctx.Unique = &unique
	return agq
}

// Order specifies how the records should be ordered.
func (agq *AccountGroupQuery) Order(o ...accountgroup.OrderOption) *AccountGroupQuery {
	agq.order = append(agq.order, o...)
	return agq
}

// First returns the first AccountGroup entity from the query.
// Returns a *NotFoundError when no AccountGroup was found.
func (agq *AccountGroupQuery) First(ctx context.Context) (*AccountGroup, error) {
	nodes, err := agq.Limit(1).All(setContextOp(ctx, agq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accountgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (agq *AccountGroupQuery) FirstX(ctx context.Context) *AccountGroup {
	node, err := agq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccountGroup ID from the query.
// Returns a *NotFoundError when no AccountGroup ID was found.
func (agq *AccountGroupQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agq.Limit(1).IDs(setContextOp(ctx, agq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accountgroup.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (agq *AccountGroupQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := agq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccountGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccountGroup entity is found.
// Returns a *NotFoundError when no AccountGroup entities are found.
func (agq *AccountGroupQuery) Only(ctx context.Context) (*AccountGroup, error) {
	nodes, err := agq.Limit(2).All(setContextOp(ctx, agq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accountgroup.Label}
	default:
		return nil, &NotSingularError{accountgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (agq *AccountGroupQuery) OnlyX(ctx context.Context) *AccountGroup {
	node, err := agq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccountGroup ID in the query.
// Returns a *NotSingularError when more than one AccountGroup ID is found.
// Returns a *NotFoundError when no entities are found.
func (agq *AccountGroupQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = agq.Limit(2).IDs(setContextOp(ctx, agq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accountgroup.Label}
	default:
		err = &NotSingularError{accountgroup.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (agq *AccountGroupQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := agq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccountGroups.
func (agq *AccountGroupQuery) All(ctx context.Context) ([]*AccountGroup, error) {
	ctx = setContextOp(ctx, agq.ctx, "All")
	if err := agq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccountGroup, *AccountGroupQuery]()
	return withInterceptors[[]*AccountGroup](ctx, agq, qr, agq.inters)
}

// AllX is like All, but panics if an error occurs.
func (agq *AccountGroupQuery) AllX(ctx context.Context) []*AccountGroup {
	nodes, err := agq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccountGroup IDs.
func (agq *AccountGroupQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if agq.ctx.Unique == nil && agq.path != nil {
		agq.Unique(true)
	}
	ctx = setContextOp(ctx, agq.ctx, "IDs")
	if err = agq.Select(accountgroup.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (agq *AccountGroupQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := agq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (agq *AccountGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, agq.ctx, "Count")
	if err := agq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, agq, querierCount[*AccountGroupQuery](), agq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (agq *AccountGroupQuery) CountX(ctx context.Context) int {
	count, err := agq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (agq *AccountGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, agq.ctx, "Exist")
	switch _, err := agq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (agq *AccountGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := agq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccountGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (agq *AccountGroupQuery) Clone() *AccountGroupQuery {
	if agq == nil {
		return nil
	}
	return &AccountGroupQuery{
		config:     agq.config,
		ctx:        agq.ctx.Clone(),
		order:      append([]accountgroup.OrderOption{}, agq.order...),
		inters:     append([]Interceptor{}, agq.inters...),
		predicates: append([]predicate.AccountGroup{}, agq.predicates...),
		// clone intermediate query.
		sql:  agq.sql.Clone(),
		path: agq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DisplayName string `json:"display_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccountGroup.Query().
//		GroupBy(accountgroup.FieldDisplayName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (agq *AccountGroupQuery) GroupBy(field string, fields ...string) *AccountGroupGroupBy {
	agq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccountGroupGroupBy{build: agq}
	grbuild.flds = &agq.ctx.Fields
	grbuild.label = accountgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DisplayName string `json:"display_name,omitempty"`
//	}
//
//	client.AccountGroup.Query().
//		Select(accountgroup.FieldDisplayName).
//		Scan(ctx, &v)
func (agq *AccountGroupQuery) Select(fields ...string) *AccountGroupSelect {
	agq.ctx.Fields = append(agq.ctx.Fields, fields...)
	sbuild := &AccountGroupSelect{AccountGroupQuery: agq}
	sbuild.label = accountgroup.Label
	sbuild.flds, sbuild.scan = &agq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccountGroupSelect configured with the given aggregations.
func (agq *AccountGroupQuery) Aggregate(fns ...AggregateFunc) *AccountGroupSelect {
	return agq.Select().Aggregate(fns...)
}

func (agq *AccountGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range agq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, agq); err != nil {
				return err
			}
		}
	}
	for _, f := range agq.ctx.Fields {
		if !accountgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if agq.path != nil {
		prev, err := agq.path(ctx)
		if err != nil {
			return err
		}
		agq.sql = prev
	}
	return nil
}

func (agq *AccountGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccountGroup, error) {
	var (
		nodes = []*AccountGroup{}
		_spec = agq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccountGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccountGroup{config: agq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, agq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (agq *AccountGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := agq.querySpec()
	_spec.Node.Columns = agq.ctx.Fields
	if len(agq.ctx.Fields) > 0 {
		_spec.Unique = agq.ctx.Unique != nil && *agq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, agq.driver, _spec)
}

func (agq *AccountGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accountgroup.Table, accountgroup.Columns, sqlgraph.NewFieldSpec(accountgroup.FieldID, field.TypeUUID))
	_spec.From = agq.sql
	if unique := agq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if agq.path != nil {
		_spec.Unique = true
	}
	if fields := agq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountgroup.FieldID)
		for i := range fields {
			if fields[i] != accountgroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := agq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := agq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := agq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := agq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (agq *AccountGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(agq.driver.Dialect())
	t1 := builder.Table(accountgroup.Table)
	columns := agq.ctx.Fields
	if len(columns) == 0 {
		columns = accountgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if agq.sql != nil {
		selector = agq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if agq.ctx.Unique != nil && *agq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range agq.predicates {
		p(selector)
	}
	for _, p := range agq.order {
		p(selector)
	}
	if offset := agq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := agq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccountGroupGroupBy is the group-by builder for AccountGroup entities.
type AccountGroupGroupBy struct {
	selector
	build *AccountGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aggb *AccountGroupGroupBy) Aggregate(fns ...AggregateFunc) *AccountGroupGroupBy {
	aggb.fns = append(aggb.fns, fns...)
	return aggb
}

// Scan applies the selector query and scans the result into the given value.
func (aggb *AccountGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aggb.build.ctx, "GroupBy")
	if err := aggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccountGroupQuery, *AccountGroupGroupBy](ctx, aggb.build, aggb, aggb.build.inters, v)
}

func (aggb *AccountGroupGroupBy) sqlScan(ctx context.Context, root *AccountGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aggb.fns))
	for _, fn := range aggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aggb.flds)+len(aggb.fns))
		for _, f := range *aggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccountGroupSelect is the builder for selecting fields of AccountGroup entities.
type AccountGroupSelect struct {
	*AccountGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ags *AccountGroupSelect) Aggregate(fns ...AggregateFunc) *AccountGroupSelect {
	ags.fns = append(ags.fns, fns...)
	return ags
}

// Scan applies the selector query and scans the result into the given value.
func (ags *AccountGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ags.ctx, "Select")
	if err := ags.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccountGroupQuery, *AccountGroupSelect](ctx, ags.AccountGroupQuery, ags, ags.inters, v)
}

func (ags *AccountGroupSelect) sqlScan(ctx context.Context, root *AccountGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ags.fns))
	for _, fn := range ags.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ags.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ags.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
