// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-consumer/ent/accountgroup"
	"go-consumer/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountgroupFields := schema.AccountGroup{}.Fields()
	_ = accountgroupFields
	// accountgroupDescID is the schema descriptor for id field.
	accountgroupDescID := accountgroupFields[0].Descriptor()
	// accountgroup.DefaultID holds the default value on creation for the id field.
	accountgroup.DefaultID = accountgroupDescID.Default.(func() uuid.UUID)
}
