// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountGroup is the predicate function for accountgroup builders.
type AccountGroup func(*sql.Selector)
